steps:
- name: 'docker.io/library/python:3.10'
  entrypoint: /bin/sh
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt && pytest']
  dir: 'src'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cloudfun0', 'http', '--runtime', 'python39', '--entry-point', 'cloudfun0']
  dir: 'src'
